#ifndef PACKETSTATUS
#define PACKETSTATUS
enum class PacketStatus
{
    INVAILD_PACKET_RANGE,
    VALID,
    INVALID_NULL,
    INVALID_CHARACTER,
    PACKET_INCOMPLETE_CREATING,
    PACKET_INCOMPLETE_ERROR,
    PACKET_USED,
    NOT_VALIDATED_YET
};
#endif